Suppress noisy output from dsymutil in bundle-mac

diff --git a/script/bundle-mac b/script/bundle-mac
--- a/script/bundle-mac
+++ b/script/bundle-mac
@@ -188,8 +188,12 @@ function prepare_binaries() {
     local architecture=$1
     local app_path=$2
 
-    echo "Unpacking dSYMs for $ architecture"
-    dsymutil --flat target/${architecture}/${target_dir}/Zed
+    echo "Unpacking dSYMs for $architecture"
+    if ! dsymutil --flat target/${architecture}/${target_dir}/Zed 2> ${target_dir}/dsymutil.log; then
+        echo "dsymmutil failed"
+        cat ${target_dir}/dsymutil.log
+        exit 1
+    fi
     version="$(cargo metadata --no-deps --manifest-path crates/zed/Cargo.toml --offline --format-version=1 | jq -r '.packages | map(select(.name == "zed"))[0].version')"
     if [ "$channel" == "nightly" ]; then
         version="$version-$(git rev-parse --short HEAD)"
