Bunch of linux work.

diff --git a/script/install-mold b/script/install-mold
--- a/script/install-mold
+++ b/script/install-mold
@@ -1,52 +1,38 @@
 #!/usr/bin/env bash
+
+# Install `mold` official binaries from GitHub Releases.
 #
-# This will install mold from pre-compiled binaries on the official GitHub
-# It is primarily used to install mold on systems that do not have a package,
-# specifically Ubuntu 20.04 and similar systems. This is necessary because
-# even compiling mold from source requires cmake >= 3.18 and Ubuntu 20.04
-# only has cmake 3.16.3.
+# Adapted from the official rui314/setup-mold@v1 action to:
+# * use environment variables instead of action inputs
+# * remove make-default support
+# * use curl instead of wget
+# * support doas for sudo
+# See: https://github.com/rui314/setup-mold/blob/main/action.yml
 
-set -euxo pipefail
+set -euo pipefail
 
-mold=$(command -v mold || true)
-if [[ -n $mold ]]; then
-  echo "Skipping install. Found mold at $mold"
-  exit 0
-elif [[ "$(uname -s)" != "Linux" ]]; then
-  echo "This script is only intended to run on Linux systems."
-  exit 1
-fi
-
-# if root or sudo is not installed, define an empty alias
-if [ "$(id -u)" -eq 0 ]; then
-    maysudo=''
-else
-    maysudo=$(command -v sudo || command -v doas || true)
-fi
-
-MOLD_VERSION="2.34.0"
-MOLD_FILE="mold-$MOLD_VERSION.tar.gz"
-
-ARCH="$(uname -m)"
-if [[ "$ARCH" == "aarch64" ]]; then
-    MOLD_URL="https://github.com/rui314/mold/releases/download/v$MOLD_VERSION/mold-$MOLD_VERSION-aarch64-linux.tar.gz"
-    MOLD_SHA256="aa8cd24aaf65564d14f6d7ff457471c3898f7e93a1827353b7ec5e82736ee93e"
-elif [[ "$ARCH" == "x86_64" ]]; then
-    MOLD_URL="https://github.com/rui314/mold/releases/download/v$MOLD_VERSION/mold-$MOLD_VERSION-x86_64-linux.tar.gz"
-    MOLD_SHA256="0405c58d9afb47dad44912faa21a8fc2f8835352434b458c3ae9665e6581d1cb"
-else
-    echo "Unsupported architecture: $ARCH"
+if [ "$(uname -s)" != "Linux" ]; then
+    echo "Error: This script is intended for Linux systems only."
     exit 1
+elif [ -z "$MOLD_VERSION" ]; then
+    echo "Usage:"
+    echo "  MOLD_VERSION=\"2.34.0\" $0"
+    exit 1
+elif /usr/local/bin/mold --version 2>/dev/null | grep -qF "$MOLD_VERSION"; then
+    echo "mold $MOLD_VERSION is already installed."
+    exit 0
+elif [ -e /usr/local/bin/mold ]; then
+    echo "Warning: existing mold found at /usr/local/bin/mold is not $MOLD_VERSION:"
+    /usr/local/bin/mold --version
+    exit
 fi
-echo "$ARCH architecture detected."
-echo "Downloading mold from $MOLD_URL"
 
-tmpdir=$(mktemp -d)
-cd "$tmpdir"
-curl -fsSL -o "$MOLD_FILE" "$MOLD_URL"
-openssl dgst -sha256 "$MOLD_FILE" | grep -q "$MOLD_SHA256"
-tar xzf "$MOLD_FILE" --strip-components=1
-rm "$MOLD_FILE"
+if [ "$(whoami)" = root ]; then SUDO=; else SUDO="$(command sudo || command doas || true)"; fi
 
-echo "Installing mold to /usr/local/"
-$maysudo cp -Rv bin lib libexec share /usr/local/
+MOLD_REPO="${MOLD_REPO:-https://github.com/rui314/mold}"
+MOLD_FILE="${MOLD_FILE:-mold-$MOLD_VERSION-$(uname -m)-linux.tar.gz}"
+MOLD_URL="${MOLD_URL:-$MOLD_REPO}/v$MOLD_VERSION/$MOLD_FILE"
+
+echo "Downloading $MOD_FILE from $MOLD_URL"
+curl --location --show-error --silent --output --retry 3 --retry-delay 5 "$MOLD_URL" \
+    | $SUDO tar -C /usr/local --strip-components=1 --no-overwrite-dir -xzf -
