Split bundle uploading and promotion into separate steps

diff --git a/script/upload-nightly b/script/upload-nightly
--- a/script/upload-nightly
+++ b/script/upload-nightly
@@ -1,7 +1,31 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # Based on the template in: https://docs.digitalocean.com/reference/api/spaces-api/
-set -ux
+bash -euo pipefail
+
+default_operation="upload_bundles"
+allowed_operations=("upload_bundles" "update_sha")
+is_allowed_operation() {
+    for val in "${allowed_operations[@]}"; do
+        if [[ "$1" == "$val" ]]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+if [[ -n "${1:-}" ]]; then
+    if is_allowed_operation "$1"; then
+        operation="$1"
+    else
+        echo "Error: Operation '$1' is not allowed."
+        echo "Usage: $0 [${allowed_operations[@]}]"
+        exit 1
+    fi
+else
+    operation="$default_operation"
+fi
+echo "Performing operation: $operation"
 
 # Step 1: Define the parameters for the Space you want to upload to.
 SPACE="zed-nightly-host" # Find your endpoint in the control panel, under Settings.
@@ -30,9 +54,19 @@ function uploadToSpaces
     "https://${SPACE}.${REGION}.digitaloceanspaces.com/${space_path}/${file_name}"
 }
 
-sha=$(git rev-parse HEAD)
-echo ${sha} > target/latest-sha
-
-# TODO kb upload the binary too
-uploadToSpaces "target/release/Zed.dmg" "Zed.dmg"
-uploadToSpaces "target/latest-sha" "latest-sha"
+case "$operation" in
+    upload_bundles)
+        find target/release -type f \( -name "*.dmg" -o -name "*.deb" \) -print0 | while IFS= read -r -d '' bundle_file; do
+            uploadToSpaces "$bundle_file" "$(basename "$bundle_file")"
+        done
+        ;;
+    update_sha)
+        sha=$(git rev-parse HEAD)
+        echo ${sha} > target/latest-sha
+        uploadToSpaces "target/latest-sha" "latest-sha"
+        ;;
+    *)
+        echo "Error: Unknown operation '$operation'"
+        exit 1
+        ;;
+esac
